grantedPermissionMap: 
  '*:*': 
    - console
  'org.alerhughes.plugin-voodoo:command.vdluck': 
    - 'm*'
  'org.alerhughes.plugin-voodoo:*': 
    - 'm*'
  'org.alerhughes.plugin-voodoo:command.vdtarot': 
    - 'm*'